project:
  type: website
  output-dir: docs

website:
  title: "GSoC-2022 Report"
  search: false
  navbar:
    right:
      - icon: github
        href: https://github.com/saradindusengupta
      - icon: twitter
        href: https://twitter.com/iamsaradindu
      - icon: linkedin
        href: https://linkedin.com/in/saradindusengupta
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

